import { Actionplan } from './actionplan';
import { User } from './user';
export class ActionSample {
    ActionDescription:String='';
    DefectDescription:String='';
    DueDate!:Date;
    Family:String='';
    Line:String='';
    Manalysis:String='';
    Progress:String='';
    Project:String='';
    Responsability:String='';
    RootCause:String='';
    SecondDueDate!:Date;
    StartDate!:Date;
    Status:String='';
    ThirdDueDate!:Date;
    DetailedStatus:String='';
    department:String='';
    Comment:String='';
    kpi:String='';
    finding:String='';
   // theme_id?:number;
    //theme?:Theme;
    user!:User;
    actionplan!:Actionplan;
    Wk0:String='';
    Wk1:String='';
    Wk2:String='';
    Wk3:String='';
    Wk4:String='';
    Wk5:String='';
    Wk6:String='';
    Wk7:String='';
    Wk8:String='';
    Wk9:String='';
    Wk10:String='';
    Wk11:String='';
    Wk12:String='';
    Wk13:String='';
    Wk14:String='';
    Wk15:String='';
    Wk16:String='';
    Wk17:String='';
    Wk18:String='';
    Wk19:String='';
    Wk20:String='';
    Wk21:String='';
    Wk22:String='';
    Wk23:String='';
    Wk24:String='';
    Wk25:String='';

}